apiVersion: v1
kind: Service
metadata:
  name: coder-service
  namespace: coder
spec:
  selector:
    app: coder-workspace
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
